services:
  postgres:
    container_name: gsl-postgres
    image: 'postgres:17.5-alpine'
    environment:
      POSTGRES_USER: dbUser
      POSTGRES_PASSWORD: secretPassword
    volumes:
      - gsl-postgres-data:/var/lib/postgresql/data/
      - ./docker/postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5432:5432'
    networks:
      - gsl-network
volumes:
  gsl-postgres-data:
    name: gsl-postgres-data

networks:
  gsl-network:
    name: gsl-network